# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15190ba17f583b4318ee3e6354c355a257ca74886c05a24898dca6bbef5471954e5db1aa8e15f357cd6a481fc08ec8b9763c4c8713647e33f942c4d583770d91

test:
  secret_key_base: ef5cd059824c02e589ebd651224abf9315761a6ea309a40d8f799dc1774767295eecf21b92954111122e9a4f649fb84e65ff3b099bd65cbb8cff0d34e09e1b29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
